### ISSUE TITLE
The plan

### ISSUE THREAD

**Issue by NotSimon5673** [FRC-1721/1721-ChargedUp#2]
**TEAMS:**
Once we have a finalized design, Software will be split up into two teams. Team 1 will be led by Keegan and team 2 will be led by your's truly. All of the code will be split up into smaller tasks, each with their own sub tasks for each member on the team to work on. This is so that nobody gets caught up on anything and so that a helping hand can be given on any issue. 

**SCHEDULE FOR SOFTWARE:**
Unlike last year, this build season will be non stop coding, as their are always improvements to be made. During the first two or so weeks we will be working on code that we will need regardless of our subsystems like drivetrain.

during the second week, we will be working on more specific projects that require a bit more info before we can code. I'd like to get started on the bot's automation during this time and also maybe start up a rough draft of our main subsystem code.

during the second and fourth week, we will work on getting all of our core designs worked on and (if everything goes according to plan) done, this is also when we will take the rough draft of our main subsystem code and turn it into something a little better.  

during the final two weeks once mechanical (hopefully) gets the robot done, we will use it for testing so we can fine tune, test, and make some needed improvements and changes. This may sound like the calmest of the weeks, as we are just testing and fixing our code, but I can assure you that couldn't be further from the truth. Knowing code team and also from personal experience I can tell you that this will easily be our most stressful weeks due to it being so close to comps AND the fact that before we get the bot,we can only guess as to what the results of our code will truly be.

even during the weeks of comp, we will most likely be doing code work, still probably mostly fine tuning and minor improvements.

**Comment by NotSimon5673** [comment]
@Kredcool @KenwoodFox is good?

**Comment by Kredcool** [comment]
This looks like the type of things I should be doing but yeah this looks like a good base.

**Comment by KenwoodFox** [comment]
This looks good, Jack and or Keegan you should maybe make a dedicated drive train branch right away and start cleaning things up, for one the example drive train uses pwm motors and we use can spark maxes. I've already added the rev libs for you in the pipfile!

I would suggest it!
