### ISSUE TITLE
Operator controls unavailable after autonomous 

### ISSUE THREAD

**Issue by KenwoodFox** [FRC-1721/1721-ChargedUp#28]
This **only** seems to happen on the field, we cannot replicate it. 

`feat/week0`

**Comment by Kredcool** [comment]
For some weird reason according to drive team driving backwards for a second fixes this

**Comment by KenwoodFox** [comment]
That sounds pretty anecdotal, more testing and more cleanup is needed. We can emulate FMS in the sim and on the robot

**Comment by Kredcool** [comment]
This issue was fixed by doing nothing
